import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, copyFile, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../src/store.js';
import { cleanProduct } from '../src/catalog.js';
import { createPlan } from '../src/planner.js';
import { saveAsset, run, probe, mediaPath } from '../src/files.js';
import { Worker } from '../src/worker.js';
import { exportDay } from '../src/export.js';
import { renderReel } from '../src/montage.js';
import { createApp } from '../src/server.js';
import { configFrom } from '../src/config.js';

test('full day renders real MP4/JPEG/SRT/ZIP, preserves portrait dimensions and republish references', {timeout:180000},async t=>{
  const preview=process.env.MARYLEE_TEST_PREVIEW_DIR;
  const dir=preview||await mkdtemp(path.join(os.tmpdir(),'marylee-render-'));await mkdir(dir,{recursive:true});
  const s=new Store(dir);t.after(async()=>{s.close();if(!preview)await rm(dir,{recursive:true,force:true});});
  s.setSettings({autoPrepare:false,voiceEnabled:true});
  const A=s.put('product',cleanProduct({name:'Тестова сукня · приклад',sku:'DEMO-A',price:1290,sizes:'S, M, L',material:'Льон',colors:'Молочний, синій',ready:true}));
  const B=s.put('product',cleanProduct({name:'Тестовий жакет · приклад',sku:'DEMO-B',price:1590,sizes:'S, M',ready:true}));
  const input=path.join(dir,'work','source.png'),clip=path.join(dir,'work','motion.mp4'),voice=path.join(dir,'work','test-voice.mp3');
  await run('ffmpeg',['-y','-f','lavfi','-i','color=c=0xd5c3ad:s=1536x1024','-frames:v','1','-threads','1',input]);
  await run('ffmpeg',['-y','-f','lavfi','-i','testsrc2=s=360x640:r=25:d=1','-c:v','libx264','-threads','1','-pix_fmt','yuv420p',clip]);
  await run('ffmpeg',['-y','-f','lavfi','-i','sine=frequency=220:duration=0.6','-c:a','libmp3lame',voice]);
  await saveAsset(s,input,{name:'photo.png',productId:A.id});await saveAsset(s,clip,{name:'video.mp4',productId:B.id});
  const plan=createPlan(s,'2026-09-10',[A.id,B.id]);
  const titles=['Один акцент — інший настрій','Збережи кольорову підказку','Яка палітра ближча?','Знайомство з сукнею','Розглянь деталь','Вечірня примірка ідей','Жакет у русі','Поділись вечірнім образом'];
  for(const [n,i] of plan.items.entries()) {i.title=titles[n];i.caption='Тестовий матеріал для перевірки застосунку. Не є товарною публікацією.';i.lines=['Спокійна основа.','Додай кольоровий акцент.'];i.hashtags=i.kind==='story'?[]:['#стиль','#marylee','#образ','#одяг','#україна'];i.pollQuestion='Яка палітра ближча?';i.pollOptions=['Спокійна','Контрастна'];}
  plan.items[0].imagePrompt='Two full-length outfits side by side, left with flats, right with boots.';s.put('plan',plan);
  let images=0,voices=0,failVoice=true;
  const ai={config:{},image:async()=>{images++;throw new Error('Image API must never run');},voice:async()=>{voices++;if(failVoice){failVoice=false;throw new Error('Voice interrupted after upload');}return voice;}};
  const app=createApp(configFrom({MARYLEE_DATA_DIR:dir}),{store:s,ai,drive:{configured:()=>false},startWorker:false});
  await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>app.server.close(resolve)));
  const base='http://127.0.0.1:'+app.server.address().port,worker=app.worker;
  const first=s.enqueue('prepare',plan.id);await worker.tick();
  assert.equal(s.job(first.id).status,'done');assert.equal(images,0);assert.equal(voices,0);
  const waiting=s.get('plan',plan.id);assert.equal(waiting.items.filter(i=>i.status==='ready').length,5);
  for(const id of ['morning','share-morning','poll'])assert.equal(waiting.items.find(i=>i.id===id).status,'awaiting-image');
  const state=await (await fetch(base+'/api/state?date='+plan.id)).json();
  assert.equal(state.setup.imageGeneration,false);assert.match(state.plan.items[0].drawingPrompt,/EXACTLY TWO/);
  const productPost=state.plan.items.find(i=>i.id==='carousel');assert.match(productPost.fullCaption,/Матеріал: Льон/);assert.match(productPost.fullCaption,/Кольори: Молочний, синій/);assert.match(productPost.goal,/характеристики/);
  assert.equal((await fetch(base+'/api/image',{method:'POST',headers:{'X-Marylee':'1'}})).status,410);
  const legacy=s.enqueue('image','legacy',{prompt:'Never draw this'});await worker.tick();assert.equal(s.job(legacy.id).status,'error');assert.equal(images,0);
  const bytes=await readFile(mediaPath(s,s.list('asset').find(a=>a.productId===A.id).file)),uploadPath=base+'/api/plans/'+plan.id+'/items/';
  assert.equal((await fetch(uploadPath+'evening/illustration?name=looks.png',{method:'POST',headers:{'X-Marylee':'1'},body:bytes})).status,400);
  const response=await fetch(uploadPath+'morning/illustration?name=looks.png',{method:'POST',headers:{'X-Marylee':'1'},body:bytes});
  const uploaded=await response.json();assert.equal(response.status,201,JSON.stringify(uploaded));
  assert.equal(uploaded.asset.layout,'diptych');assert.equal(s.get('plan',plan.id).items[0].illustrationId,uploaded.asset.id);
  await worker.tick();assert.equal(s.job(uploaded.job.id).status,'error');assert.equal(images,0);
  const retry=s.enqueue('prepare',plan.id);await worker.tick();assert.equal(s.job(retry.id).status,'done',s.job(retry.id).message);
  assert.equal(images,0,'upload and retry never call the image provider');assert.equal(voices,3,'only two morning lines plus the failed call; no sales voice calls');
  assert.equal(s.get('plan',plan.id).items[0].illustrationId,uploaded.asset.id,'voice retry preserves the uploaded illustration');
  const ready=s.get('plan',plan.id);assert.ok(ready.items.every(i=>i.status==='ready'));
  for(const id of ['morning','evening']) {
    const reel=ready.items.find(i=>i.id===id),media=s.get('asset',reel.outputIds[0]);const info=await probe(mediaPath(s,media.file));
    const v=info.streams.find(x=>x.codec_type==='video'),audio=info.streams.find(x=>x.codec_type==='audio');const firstFrame=await run('ffmpeg',['-i',mediaPath(s,media.file),'-frames:v','1','-vf','signalstats,metadata=print','-f','null','-']);const brightness=Number(firstFrame.stderr.match(/lavfi.signalstats.YAVG=([\d.]+)/)[1]);assert.ok(brightness>25,'first frame must show content, not a black fade');assert.equal(v.width,1080);assert.equal(v.height,1920);assert.equal(v.pix_fmt,'yuv420p');assert.equal(audio.codec_name,'aac');assert.equal(Number(audio.sample_rate),48000);assert.equal(audio.channels,2);assert.ok(Math.abs(Number(info.format.duration)-reel.duration)<.2);
  }
  assert.deepEqual(ready.items.find(i=>i.id==='share-evening').outputIds,ready.items.find(i=>i.id==='evening').outputIds);
  const zip=await exportDay(s,plan.id);const listing=(await run('unzip',['-Z1',zip])).stdout;assert.match(listing,/09-00-morning\/1.mp4|09-00-morning\/01.mp4/);assert.match(listing,/12-00-poll\/instructions.txt/);assert.match(listing,/START-HERE.txt/);
  const jpg=s.get('asset',ready.items.find(i=>i.id==='carousel').outputIds[0]);const imageInfo=await probe(mediaPath(s,jpg.file));assert.equal(imageInfo.streams[0].width,1080);assert.equal(imageInfo.streams[0].height,1350);
  const productPhoto=s.list('asset').find(a=>a.productId===A.id);
  const photoReel={...ready.items.find(i=>i.id==='evening'),productId:A.id,selectedAssetIds:[productPhoto.id],notes:[]};
  const work=path.join(dir,'work','photo-reel');await mkdir(work,{recursive:true});
  await renderReel(s,ai,ready,photoReel,work);assert.equal(photoReel.voiceUsed,false);assert.match(photoReel.notes.join(' '),/Без озвучки/);assert.equal(voices,3);const silence=await run('ffmpeg',['-i',mediaPath(s,s.get('asset',photoReel.outputIds[0]).file),'-vn','-af','volumedetect','-f','null','-']);const maximum=Number(silence.stderr.match(/max_volume: (-?[\d.]+) dB/)[1]);assert.ok(maximum<=-80,`sales audio must be silent: ${maximum}dB`);
  const editorialInput=path.join(dir,'work','editorial.png');await copyFile(mediaPath(s,productPhoto.file),editorialInput);
  const editorial=await saveAsset(s,editorialInput,{name:'editorial.png',source:'ai'});
  const educational={...ready.items.find(i=>i.id==='morning'),selectedAssetIds:[editorial.id],notes:[]};
  await renderReel(s,ai,ready,educational,work);assert.equal(educational.kind,'reel');assert.equal(educational.voiceUsed,true);assert.ok(educational.outputIds.length>0);
  const changed=await fetch(uploadPath+'morning',{method:'PUT',headers:{'X-Marylee':'1','Content-Type':'application/json'},body:JSON.stringify({imagePrompt:'A different pair of outfits with a red bag.'})});assert.equal(changed.status,200);
  const changedPlan=s.get('plan',plan.id);assert.equal(changedPlan.items[0].illustrationId,null);assert.deepEqual(changedPlan.items[0].selectedAssetIds,[]);
  s.enqueue('prepare',plan.id);await worker.tick();assert.equal(s.get('plan',plan.id).items[0].status,'awaiting-image');assert.equal(images,0);
  assert.ok(s.get('asset',uploaded.asset.id),'old uploaded file is preserved');
  if(preview)console.log('Preview data:',dir);
});
